In [4]:
a <- c(1,2,3,4)

In [15]:
a[-1]

[1] 2 3 4

In [16]:
a[-2]

[1] 1 3 4

In [20]:
a[a > 2]

[1] 3 4

In [36]:
T

[1] TRUE

In [77]:
TRUE

[1] TRUE

---
# list

In [78]:
list(1, 2, 3)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

---
# matrix

In [41]:
A <- matrix(1:12, ncol=4, byrow=T)

In [42]:
A

[,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12

## transpose

In [44]:
t(A)

[,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

---
## element-wise power

In [45]:
A^2

[,1] [,2] [,3] [,4]
[1,]    1    4    9   16
[2,]   25   36   49   64
[3,]   81  100  121  144

----
## array inter product / outer product

In [46]:
A <- matrix(1:9, ncol=3)

In [47]:
A %*% A

[,1] [,2] [,3]
[1,]   30   66  102
[2,]   36   81  126
[3,]   42   96  150

In [48]:
A %o% A

, , 1, 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2, 1

     [,1] [,2] [,3]
[1,]    2    8   14
[2,]    4   10   16
[3,]    6   12   18

, , 3, 1

     [,1] [,2] [,3]
[1,]    3   12   21
[2,]    6   15   24
[3,]    9   18   27

, , 1, 2

     [,1] [,2] [,3]
[1,]    4   16   28
[2,]    8   20   32
[3,]   12   24   36

, , 2, 2

     [,1] [,2] [,3]
[1,]    5   20   35
[2,]   10   25   40
[3,]   15   30   45

, , 3, 2

     [,1] [,2] [,3]
[1,]    6   24   42
[2,]   12   30   48
[3,]   18   36   54

, , 1, 3

     [,1] [,2] [,3]
[1,]    7   28   49
[2,]   14   35   56
[3,]   21   42   63

, , 2, 3

     [,1] [,2] [,3]
[1,]    8   32   56
[2,]   16   40   64
[3,]   24   48   72

, , 3, 3

     [,1] [,2] [,3]
[1,]    9   36   63
[2,]   18   45   72
[3,]   27   54   81

----
## Solve linear system

In [64]:
A <- diag(c(1, 1, 1))

In [67]:
solve(A, c(5, 4, 3))

[1] 5 4 3

## inverse

In [69]:
solve(A)

[,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1

---
## DataFrame

In [70]:
?data.frame

data.frame                package:base                 R Documentation

_D_a_t_a _F_r_a_m_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     This function creates data frames, tightly coupled collections of
     variables which share many of the properties of matrices and of
     lists, used as the fundamental data structure by most of R's
     modeling software.

_U_s_a_g_e:

     data.frame(..., row.names = NULL, check.rows = FALSE,
                check.names = TRUE,
                stringsAsFactors = default.stringsAsFactors())
     
     default.stringsAsFactors()
     
_A_r_g_u_m_e_n_t_s:

     ...: these arguments are of either the form ‘value’ or ‘tag =
          value’.  Component names are created based on the tag (if
          present) or the deparsed argument itself.

row.names: ‘NULL’ or a single integer or character string specifying a
          column to be used as row names, or a character or integer
          vector giving the row names for the data frame.

check.rows: if ‘TRUE’ then the rows are checked for consistency of
          length and names.

check.names: logical.  If ‘TRUE’ then the names of the variables in the
          data frame are checked to ensure that they are syntactically
          valid variable names and are not duplicated.  If necessary
          they are adjusted (by ‘make.names’) so that they are.

stringsAsFactors: logical: should character vectors be converted to
          factors?  The ‘factory-fresh’ default is ‘TRUE’, but this can
          be changed by setting ‘options(stringsAsFactors = FALSE)’.

_D_e_t_a_i_l_s:

     A data frame is a list of variables of the same number of rows
     with unique row names, given class ‘"data.frame"’.  If no
     variables are included, the row names determine the number of
     rows.

     The column names should be non-empty, and attempts to use empty
     names will have unsupported results.  Duplicate column names are
     allowed, but you need to use ‘check.names = FALSE’ for
     ‘data.frame’ to generate such a data frame.  However, not all
     operations on data frames will preserve duplicated column names:
     for example matrix-like subsetting will force column names in the
     result to be unique.

     ‘data.frame’ converts each of its arguments to a data frame by
     calling ‘as.data.frame(optional = TRUE)’.  As that is a generic
     function, methods can be written to change the behaviour of
     arguments according to their classes: R comes with many such
     methods.  Character variables passed to ‘data.frame’ are converted
     to factor columns unless protected by ‘I’ or argument
     ‘stringsAsFactors’ is false.  If a list or data frame or matrix is
     passed to ‘data.frame’ it is as if each component or column had
     been passed as a separate argument (except for matrices of class
     ‘"model.matrix"’ and those protected by ‘I’).

     Objects passed to ‘data.frame’ should have the same number of
     rows, but atomic vectors (see ‘is.vector’), factors and character
     vectors protected by ‘I’ will be recycled a whole number of times
     if necessary (including as elements of list arguments).

     If row names are not supplied in the call to ‘data.frame’, the row
     names are taken from the first component that has suitable names,
     for example a named vector or a matrix with rownames or a data
     frame.  (If that component is subsequently recycled, the names are
     discarded with a warning.)  If ‘row.names’ was supplied as ‘NULL’
     or no suitable component was found the row names are the integer
     sequence starting at one (and such row names are considered to be
     ‘automatic’, and not preserved by ‘as.matrix’).

     If row names are supplied of length one and the data frame has a
     single row, the ‘row.names’ is taken to specify the row names and
     not a column (by name or number).

     Names are removed from vector inputs not protected by ‘I’.

     ‘default

---
## plot

In [71]:
?plot

plot                 package:graphics                  R Documentation

_G_e_n_e_r_i_c _X-_Y _P_l_o_t_t_i_n_g

_D_e_s_c_r_i_p_t_i_o_n:

     Generic function for plotting of R objects.  For more details
     about the graphical parameter arguments, see ‘par’.

     For simple scatter plots, ‘plot.default’ will be used.  However,
     there are ‘plot’ methods for many R objects, including
     ‘function’s, ‘data.frame’s, ‘density’ objects, etc.  Use
     ‘methods(plot)’ and the documentation for these.

_U_s_a_g_e:

     plot(x, y, ...)
     
_A_r_g_u_m_e_n_t_s:

       x: the coordinates of points in the plot. Alternatively, a
          single plotting structure, function or _any R object with a
          ‘plot’ method_ can be provided.

       y: the y coordinates of points in the plot, _optional_ if ‘x’ is
          an appropriate structure.

     ...: Arguments to be passed to methods, such as graphical
          parameters (see ‘par’).  Many methods will accept the
          following arguments:

          ‘type’ what type of plot should be drawn.  Possible types are

                • ‘"p"’ for *p*oints,

                • ‘"l"’ for *l*ines,

                • ‘"b"’ for *b*oth,

                • ‘"c"’ for the lines part alone of ‘"b"’,

                • ‘"o"’ for both ‘*o*verplotted’,

                • ‘"h"’ for ‘*h*istogram’ like (or ‘high-density’)
                  vertical lines,

                • ‘"s"’ for stair *s*teps,

                • ‘"S"’ for other *s*teps, see ‘Details’ below,

                • ‘"n"’ for no plotting.

              All other ‘type’s give a warning or an error; using,
              e.g., ‘type = "punkte"’ being equivalent to ‘type = "p"’
              for S compatibility.  Note that some methods, e.g.
              ‘plot.factor’, do not accept this.

          ‘main’ an overall title for the plot: see ‘title’.

          ‘sub’ a sub title for the plot: see ‘title’.

          ‘xlab’ a title for the x axis: see ‘title’.

          ‘ylab’ a title for the y axis: see ‘title’.

          ‘asp’ the y/x aspect ratio, see ‘plot.window’.

_D_e_t_a_i_l_s:

     The two step types differ in their x-y preference: Going from
     (x1,y1) to (x2,y2) with x1 < x2, ‘type = "s"’ moves first
     horizontal, then vertical, whereas ‘type = "S"’ moves the other
     way around.

_S_e_e _A_l_s_o:

     ‘plot.default’, ‘plot.formula’ and other methods; ‘points’,
     ‘lines’, ‘par’.

     For X-Y-Z plotting see ‘contour’, ‘persp’ and ‘image’.

_E_x_a_m_p_l_e_s:

     require(stats) # for lowess, rpois, rnorm
     plot(cars)
     lines(lowess(cars))
     
     plot(sin, -pi, 2*pi) # see ?plot.function
     
     ## Discrete Distribution Plot:
     plot(table(rpois(100, 5)), type = "h", col = "red", lwd = 10,
          main = "rpois(100, lambda = 5)")
     
     ## Simple quantiles/ECDF, see ecdf() {library(stats)} for a better one:
     plot(x <- sort(rnorm(47)), type = "s", main = "plot(x, type = \"s\")")
     points(x, cex = .5, col = "dark red")

---
# CRAN

In [73]:
install.packages('ggplot2')

ERROR: Error in contrib.url(repos, type): trying to use CRAN without setting a mirror


In [74]:
library('ggplot2')

----
# Flow Control

- apply
- sapply
- lapply

In [76]:
?apply

apply                   package:base                   R Documentation

_A_p_p_l_y _F_u_n_c_t_i_o_n_s _O_v_e_r _A_r_r_a_y _M_a_r_g_i_n_s

_D_e_s_c_r_i_p_t_i_o_n:

     Returns a vector or array or list of values obtained by applying a
     function to margins of an array or matrix.

_U_s_a_g_e:

     apply(X, MARGIN, FUN, ...)
     
_A_r_g_u_m_e_n_t_s:

       X: an array, including a matrix.

  MARGIN: a vector giving the subscripts which the function will be
          applied over.  E.g., for a matrix ‘1’ indicates rows, ‘2’
          indicates columns, ‘c(1, 2)’ indicates rows and columns.
          Where ‘X’ has named dimnames, it can be a character vector
          selecting dimension names.

     FUN: the function to be applied: see ‘Details’.  In the case of
          functions like ‘+’, ‘%*%’, etc., the function name must be
          backquoted or quoted.

     ...: optional arguments to ‘FUN’.

_D_e_t_a_i_l_s:

     If ‘X’ is not an array but an object of a class with a non-null
     ‘dim’ value (such as a data frame), ‘apply’ attempts to coerce it
     to an array via ‘as.matrix’ if it is two-dimensional (e.g., a data
     frame) or via ‘as.array’.

     ‘FUN’ is found by a call to ‘match.fun’ and typically is either a
     function or a symbol (e.g., a backquoted name) or a character
     string specifying a function to be searched for from the
     environment of the call to ‘apply’.

     Arguments in ‘...’ cannot have the same name as any of the other
     arguments, and care may be needed to avoid partial matching to
     ‘MARGIN’ or ‘FUN’.  In general-purpose code it is good practice to
     name the first three arguments if ‘...’ is passed through: this
     both avoids partial matching to ‘MARGIN’ or ‘FUN’ and ensures that
     a sensible error message is given if arguments named ‘X’, ‘MARGIN’
     or ‘FUN’ are passed through ‘...’.

_V_a_l_u_e:

     If each call to ‘FUN’ returns a vector of length ‘n’, then ‘apply’
     returns an array of dimension ‘c(n, dim(X)[MARGIN])’ if ‘n > 1’.
     If ‘n’ equals ‘1’, ‘apply’ returns a vector if ‘MARGIN’ has length
     1 and an array of dimension ‘dim(X)[MARGIN]’ otherwise.  If ‘n’ is
     ‘0’, the result has length 0 but not necessarily the ‘correct’
     dimension.

     If the calls to ‘FUN’ return vectors of different lengths, ‘apply’
     returns a list of length ‘prod(dim(X)[MARGIN])’ with ‘dim’ set to
     ‘MARGIN’ if this has length greater than one.

     In all cases the result is coerced by ‘as.vector’ to one of the
     basic vector types before the dimensions are set, so that (for
     example) factor results will be coerced to a character array.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘lapply’ and there, ‘simplify2array’; ‘tapply’, and convenience
     functions ‘sweep’ and ‘aggregate’.

_E_x_a_m_p_l_e_s:

     ## Compute row and column sums for a matrix:
     x <- cbind(x1 = 3, x2 = c(4:1, 2:5))
     dimnames(x)[[1]] <- letters[1:8]
     apply(x, 2, mean, trim = .2)
     col.sums <- apply(x, 2, sum)
     row.sums <- apply(x, 1, sum)
     rbind(cbind(x, Rtot = row.sums), Ctot = c(col.sums, sum(col.sums)))
     
     stopifnot( apply(x, 2, is.vector))
     
     ## Sort the columns of a matrix
     apply(x, 2, sort)
     
     ## keeping named dimnames
     names(dimnames(x)) <- c("row", "col")
     x3 <- array(x, dim = c(dim(x),3),
                 dimnames = c(dimnames(x), list(C = paste0("cop.",1:3))))
     identical(x,  apply( x,  2,  identity))
     identical(x3, apply(x3, 2:3, identity))
     
     ##- function with extra args:
     cave <- function(x, c1, c2) c(mean(x[c1]), mean(x[c2]))
     apply(x, 1, cave,  c1 = "x1", c2 = c("x1","x2"))
     
     ma <- matrix(c(1:4, 1, 6:8), nrow = 2)
     ma
     apply(ma, 1, table)  #--> a list of 

---
# function

In [79]:
f <- function(x) x^2

In [85]:
f(c(2, 3, 4))

[1]  4  9 16

---

In [82]:
a <- c(2, 3, 4)

In [84]:
append(a, c(4 , 5, 3))

[1] 2 3 4 4 5 3

---



In [87]:
?rm

remove                  package:base                   R Documentation

_R_e_m_o_v_e _O_b_j_e_c_t_s _f_r_o_m _a _S_p_e_c_i_f_i_e_d _E_n_v_i_r_o_n_m_e_n_t

_D_e_s_c_r_i_p_t_i_o_n:

     ‘remove’ and ‘rm’ can be used to remove objects.  These can be
     specified successively as character strings, or in the character
     vector ‘list’, or through a combination of both.  All objects thus
     specified will be removed.

     If ‘envir’ is NULL then the currently active environment is
     searched first.

     If ‘inherits’ is ‘TRUE’ then parents of the supplied directory are
     searched until a variable with the given name is encountered.  A
     warning is printed for each variable that is not found.

_U_s_a_g_e:

     remove(..., list = character(), pos = -1,
            envir = as.environment(pos), inherits = FALSE)
     
     rm    (..., list = character(), pos = -1,
            envir = as.environment(pos), inherits = FALSE)
     
_A_r_g_u_m_e_n_t_s:

     ...: the objects to be removed, as names (unquoted) or character
          strings (quoted).

    list: a character vector naming objects to be removed.

     pos: where to do the removal.  By default, uses the current
          environment.  See ‘details’ for other possibilities.

   envir: the ‘environment’ to use.  See ‘details’.

inherits: should the enclosing frames of the environment be inspected?

_D_e_t_a_i_l_s:

     The ‘pos’ argument can specify the environment from which to
     remove the objects in any of several ways: as an integer (the
     position in the ‘search’ list); as the character string name of an
     element in the search list; or as an ‘environment’ (including
     using ‘sys.frame’ to access the currently active function calls).
     The ‘envir’ argument is an alternative way to specify an
     environment, but is primarily there for back compatibility.

     It is not allowed to remove variables from the base environment
     and base namespace, nor from any environment which is locked (see
     ‘lockEnvironment’).

     Earlier versions of R incorrectly claimed that supplying a
     character vector in ‘...’ removed the objects named in the
     character vector, but it removed the character vector.  Use the
     ‘list’ argument to specify objects _via_ a character vector.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘ls’, ‘objects’

_E_x_a_m_p_l_e_s:

     tmp <- 1:4
     ## work with tmp  and cleanup
     rm(tmp)
     
     ## Not run:
     
     ## remove (almost) everything in the working environment.
     ## You will get no warning, so don't do this unless you are really sure.
     rm(list = ls())
     ## End(Not run)